version: "3.5"

services: 
  clion_remote:
    image: essethon/clion-remote:ohmybash
    container_name: "clion_remote_env"
    ports: 
      - "127.0.0.1:2223:22"
    volumes: 
      - ${HOME}/.ssh/authorized_keys:/home/user/.ssh/authorized_keys:ro
    cap_add: 
      - sys_ptrace
    restart: unless-stopped